- Source/Network.swift
Cannot force unwrap value of non-optional type 'NSURLSessionDataTask' (XCode7 Beta 4)
> Xcode7 Beta 4

- Source/Query.swift
"&".join has changed to .joinWithSeparator("&")
> Swift2 - Xcode7b4

- ChangeLog
- Source/Query.swift
Exactly the same as Objective-C.
Waiting your agreement to release it :smile:
> Add new geo-search

- Tests/ClientTests.swift
- Tests/Helpers.swift
> Test Keep-Alive connection

- Source/Network.swift
If the original request resulted in an error, this logic was overriding the error from the completion handler resulting in a `nil` error passed to the block:
`let (JSON, error) = self.serializeResponse(data)`
I actually introduced this bug a while ago with some other changes and we've only just caught it :see_no_evil:
> Prevent request error being overwritten

- .travis.yml
- AlgoliaSearch.xcodeproj/project.pbxproj
- AlgoliaSearch.xcodeproj/xcshareddata/xcschemes/AlgoliaSearch tvOS.xcscheme
- run_test.sh
> Add support for tvOS

- Source/Client.swift
- Source/Helpers.swift
> Shuffle host array at client init

- Tests/IndexTests.swift
> Add test case for DNS resolution time-out

- ChangeLog.md
- Source/Query.swift
- Tests/QueryTests.swift
> Accept a list of languages as `removeStopWords` value

- ChangeLog.md
- Source/Query.swift
- Tests/QueryTests.swift
> Support `aroundRadius=all` in query parameters

- Source/Index.swift
- Tests/IndexTests.swift
> Implement the `forwardToSlaves` parameter when changing index settings

- AlgoliaSearch-Client-Swift.podspec
Hello,
I've added and tested the framework on tvOS and it seems to be working well. Could you merge it?
Thanks!
> tvOS Podspec

- AlgoliaSearch-Client-Swift.podspec
- AlgoliaSearch.xcodeproj/project.pbxproj
- AlgoliaSearch.xcodeproj/xcshareddata/xcschemes/AlgoliaSearch watchOS.xcscheme
NOTE: watchOS [does not support unit testing](http://stackoverflow.com/questions/33756093/watchos-unit-testing) so far.
Fixes #118.
> Add support for watchOS

- Source/Index.swift
- Tests/IndexTests.swift
> Add an `Index.getObjects()` method with attributes to retrieve

- .jazzy.yaml
- AlgoliaSearch.xcodeproj/project.pbxproj
- Source/AbstractClient.swift
- Source/AbstractQuery.swift
- Source/Client.swift
- Source/PlacesClient.swift
- Source/PlacesQuery.swift
- Source/Query.swift
- Source/Types.swift
- Tests/ObjectiveCBridging.m
- Tests/PlacesClientTests.swift
- Tests/PlacesQueryTests.swift
- offline.jazzy.yaml
- run_test.sh
> Add support for Algolia Places

- Source/Query.swift
- Tests/ObjectiveCBridging.m
- Tests/QueryTests.swift
**Warning:** Breaking change (for this parameter only).
> Support a union of polygons in the `insidePolygon` query parameter

- Source/Network.swift
- Tests/ClientTests.swift
- Tests/IndexTests.swift
- Tests/NetworkTests.swift
- Tests/ObjectiveCBridging.m
- Tests/Offline/MirroredIndexTests.swift
- Tests/Offline/OfflineObjcBridging.m
- Tests/OnlineTestCase.swift
**Note:** This is an ongoing effort. **Do not merge** until final version is released.
Fixes #291.
> Swift 3.1 compliance

- Source/Query.swift
- Tests/ObjectiveCBridging.m
- Tests/QueryTests.swift
3 params added to the client in order to support all params in the doc:
- offset
- length
- disableExactOnAttributes
> Add 3 params: offset, length, disableExactOnAttributes

- Source/Cache.swift
- Source/Query.swift
- Tests/ObjectiveCBridging.m
- Tests/QueryTests.swift
Implement `ruleContexts` and `enableRules` param.
> feat(query-rules): add query rules support

- fastlane/Fastfile
We also clean the destination directory in 1727dea
> feat(fastlane): add "deploy api reference" to fastlane

- README.md
> Clarify that this library can be used in Objective-C

- Sources/AlgoliaSearch-Client/Index.swift
It was missing the facets coming from disjunctiveFacets found in `SearchParameters` and not in `Query` class
> Solve issue when doing a SFFV with disjunctive facets

- InstantSearchClient.podspec
- InstantSearchClientOffline.podspec
- Sources/Info.plist
- Tests/Info.plist
> Deploying new minor version 6.2.0

- InstantSearchClient.podspec
- InstantSearchClientOffline.podspec
- Sources/Info.plist
- Tests/Info.plist
> Deploying new minor version 6.3.0

- InstantSearchClient.podspec
- InstantSearchClientOffline.podspec
- Sources/Info.plist
- Tests/Info.plist
> Deploying new major version 7.0.0

- AlgoliaSearch.xcodeproj/project.pbxproj
- Gemfile
- Gemfile.lock
- InstantSearchClient.podspec
- Podfile
- Podfile.lock
- Tests/Info.plist
> Release 7.0.3

- AlgoliaSearch.xcodeproj/project.pbxproj
- InstantSearchClient.podspec
- InstantSearchClientOffline.podspec
- Sources/AlgoliaSearch-Client/Version.swift
- Sources/Info.plist
- Tests/Info.plist
> Deploying new patch version 7.0.4

- AlgoliaSearch.xcodeproj/project.pbxproj
- InstantSearchClient.podspec
- InstantSearchClientOffline.podspec
- Sources/AlgoliaSearch-Client/Version.swift
- Sources/Info.plist
- Tests/Info.plist
> Deploying new patch version 7.0.5

- Sources/AlgoliaSearchClientSwift/Models/Query/Query+Codable.swift
- Sources/AlgoliaSearchClientSwift/Models/Query/Query+URLEncodable.swift
- Sources/AlgoliaSearchClientSwift/Models/Query/Query.swift
- Tests/AlgoliaSearchClientSwiftTests/Unit/QueryTests.swift
> feat(query): add naturalLanguages parameter

- Sources/AlgoliaSearchClient/Helpers/Coding/Wrappers/BoolContainer.swift
- Sources/AlgoliaSearchClient/Helpers/Coding/Wrappers/StringNumberContainer.swift
- Sources/AlgoliaSearchClient/Models/Rule/Rule+Alternatives.swift
- Sources/AlgoliaSearchClient/Models/Search/Indexing/PartialUpdate.swift
- Sources/AlgoliaSearchClient/Models/Settings/Auxiliary/LanguageFeature.swift
- Tests/AlgoliaSearchClientTests/Doc/APIParameters/APIParameters+Typos.swift
- Tests/AlgoliaSearchClientTests/Doc/Methods/ABTestSnippets.swift
- Tests/AlgoliaSearchClientTests/Doc/Methods/RulesSnippets.swift
- Tests/AlgoliaSearchClientTests/Helper/XCTest+Codable.swift
- Tests/AlgoliaSearchClientTests/Integration/QueryRulesIntegrationTests.swift
- Tests/AlgoliaSearchClientTests/Unit/ObjectCreationTests.swift
- Tests/AlgoliaSearchClientTests/Unit/Rule/RuleAlternativesTests.swift
- Tests/AlgoliaSearchClientTests/Unit/Rule/RuleConditionTests.swift
- Tests/AlgoliaSearchClientTests/Unit/Rule/RuleTests.swift
- Tests/AlgoliaSearchClientTests/Unit/Settings/LanguageFeatureTests.swift
- Tests/AlgoliaSearchClientTests/Unit/TestValues.swift
> Ensure bool-representable enums deserialization from string

- Sources/AlgoliaSearchClient/Models/Search/Indexing/PartialUpdate.swift
- Tests/AlgoliaSearchClientTests/Unit/PartialUpdateTests.swift
This PR add `IncrementSet` and `IncrementFrom` partial update operations.
Resolves #638
> Add IncrementSet and IncrementFrom as partial update operations. 

- Sources/AlgoliaSearchClient/Models/Rule/Rule.swift
- Tests/AlgoliaSearchClientTests/Doc/APIParameters/APIParameters+Rules.swift
- Tests/AlgoliaSearchClientTests/Doc/Methods/RulesSnippets.swift
- Tests/AlgoliaSearchClientTests/Integration/BrowseIntegrationTests.swift
- Tests/AlgoliaSearchClientTests/Integration/CopyIndexIntegrationTests.swift
- Tests/AlgoliaSearchClientTests/Integration/QueryRulesIntegrationTests.swift
- Tests/AlgoliaSearchClientTests/Unit/Rule/RuleTests.swift
- Tests/AlgoliaSearchClientTests/Unit/TestValues.swift
This PR implements multi-condition query rules feature. 
Resolves #637
> Multi-condition query rules

- Sources/AlgoliaSearchClient/Client/Search/SearchClient.swift
- Sources/AlgoliaSearchClient/Models/Common/UserToken.swift
- Sources/AlgoliaSearchClient/Models/Search/Indexing/Scope.swift
- Sources/AlgoliaSearchClient/Models/Search/Response/SearchResponse/Auxiliary/Alternative/AlternativeType.swift
- Sources/AlgoliaSearchClient/Models/Task/Common/TaskStatus.swift
- Tests/AlgoliaSearchClientTests/Helper/XCTest+Codable.swift
- Tests/AlgoliaSearchClientTests/Helper/XCTest+HTTPError.swift
- Tests/AlgoliaSearchClientTests/Helper/XCTest+Wait.swift
- Tests/AlgoliaSearchClientTests/Integration/APIKeysIntegrationTests.swift
- Tests/AlgoliaSearchClientTests/Integration/AnalyticsIntegrationsTests.swift
- Tests/AlgoliaSearchClientTests/Integration/BatchingIntegrationsTests.swift
- Tests/AlgoliaSearchClientTests/Integration/BrowseIntegrationTests.swift
- Tests/AlgoliaSearchClientTests/Integration/CopyIndexIntegrationTests.swift
- Tests/AlgoliaSearchClientTests/Integration/ExistsIntegrationTests.swift
- Tests/AlgoliaSearchClientTests/Integration/IndexingIntegrationTests.swift
- Tests/AlgoliaSearchClientTests/Integration/InsightsIntegrationTests.swift
- Tests/AlgoliaSearchClientTests/Integration/LogsIntergrationTests.swift
- Tests/AlgoliaSearchClientTests/Integration/MultiClusterIntegrationTests.swift
- Tests/AlgoliaSearchClientTests/Integration/MultipleOperationsIntegrationTests.swift
- Tests/AlgoliaSearchClientTests/Integration/OnlineTestCase.swift
- Tests/AlgoliaSearchClientTests/Integration/PersonalizationIntegrationTests.swift
- Tests/AlgoliaSearchClientTests/Integration/QueryRulesIntegrationTests.swift
- Tests/AlgoliaSearchClientTests/Integration/SearchIntegrationTests.swift
- Tests/AlgoliaSearchClientTests/Integration/SecuredAPIKeysIntegrationTests.swift
- Tests/AlgoliaSearchClientTests/Integration/SettingsIntegrationTests.swift
- Tests/AlgoliaSearchClientTests/Integration/SynonymsIntegrationTests.swift
- Tests/AlgoliaSearchClientTests/Unit/Command/AlgoliaCommandTest.swift
- Add Xcode 12 compatibility
- Add `Client` typealias for `SearchClient` to simplify the transition from v7
> Release 8.0.1

- AlgoliaSearchClient.podspec
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> Deploying new patch version 8.0.1

- AlgoliaSearchClient.podspec
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> Deploying new minor version 8.1.0

- Sources/AlgoliaSearchClient/Command/Command+Personalization.swift
- Sources/AlgoliaSearchClient/Command/Command+Search.swift
- Sources/AlgoliaSearchClient/Models/Internal/HTTP/HTTPStatusCode.swift
- Sources/AlgoliaSearchClient/Models/Places/PlacesQuery.swift
- Sources/AlgoliaSearchClient/Transport/HTTP/HTTPRequest.swift
- Sources/AlgoliaSearchClient/Transport/HTTP/HTTPRequestBuilder.swift
- Sources/AlgoliaSearchClient/Transport/HTTP/HTTPTransport+Error.swift
- Sources/AlgoliaSearchClient/Transport/HTTP/HTTPTransport+Result.swift
- Sources/AlgoliaSearchClient/Transport/RetryStrategy/AlgoliaRetryStrategy.swift
- Sources/AlgoliaSearchClient/Transport/RetryStrategy/HostIterator.swift
- Sources/AlgoliaSearchClient/Transport/RetryStrategy/RetryStrategy.swift
- Sources/AlgoliaSearchClient/Transport/URLSession/URLRequest+Convenience.swift
- Tests/AlgoliaSearchClientTests/Doc/ManagingResults/DetectingIntentSnippets.swift
- Tests/AlgoliaSearchClientTests/Doc/Methods/IndexingSnippets.swift
- Tests/AlgoliaSearchClientTests/Doc/Methods/PersonalizationSnippets.swift
- Tests/AlgoliaSearchClientTests/Integration/AnalyticsIntegrationsTests.swift
- Tests/AlgoliaSearchClientTests/Integration/OnlineTestCase.swift
- Tests/AlgoliaSearchClientTests/Integration/PersonalizationIntegrationTests.swift
- Tests/AlgoliaSearchClientTests/Unit/AlgoliaRetryStrategyTests.swift
- Tests/AlgoliaSearchClientTests/Unit/Command/PersonalizationCommandTests.swift
- Tests/AlgoliaSearchClientTests/Unit/Command/SearchCommandTests.swift
- Tests/AlgoliaSearchClientTests/Unit/TestValues.swift
This PR includes:
- Patch #663 
- Patch #665 
- Usage of generated indices names in the Analytics tests to avoid integration tests flakiness
> Release 8.1.1

- AlgoliaSearchClient.podspec
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> Deploying new patch version 8.1.1

- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
**Summary**
Restore 8.1.1 patch version from beta for correct release process of the next version
> Restore patch version

- AlgoliaSearchClient.podspec
**Summary**
Restore podspec patch version from beta for correct release process of the next version
> Restore podspec patch version

- AlgoliaSearchClient.podspec
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> Deploying new patch version 8.1.2

- fastlane/Fastfile
- generate_changelog
**Summary**
- Automatic changelog and release note generation using _polyglot_ tool
- Add comments to **generate_version** script
> ci: Full deployment automation

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new patch version 8.1.3

- README.md
**Summary**
Update readme with a relevant version to avoid the installation of the outdated version of the Client.
> docs: Update readme with a relevant version

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new minor version 8.2.0

- README.md
> fix: license link in Readme

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new minor version 8.3.0

- .github/semantic.yml
- README.md
Update version and platform badge
> chore: Update readme version & platforms

- Package.swift
- Sources/AlgoliaSearchClient/Client/Search/SearchClient+MultiCluster.swift
- Sources/AlgoliaSearchClient/Helpers/Coding/Wrappers/BoolContainer.swift
- Sources/AlgoliaSearchClient/Helpers/Crypto/String+HMAC.swift
- Sources/AlgoliaSearchClient/Helpers/String/String+Wrapping.swift
- Sources/AlgoliaSearchClient/Index/Index+Synonym.swift
- Sources/AlgoliaSearchClient/Models/Internal/Path/Path.swift
- Sources/AlgoliaSearchClient/Models/Internal/Path/PathComponent.swift
- Sources/AlgoliaSearchClient/Models/Rule/Rule+Alternatives.swift
- Sources/AlgoliaSearchClient/Models/Search/Hit/Hit.swift
- Sources/AlgoliaSearchClient/Models/Search/Indexing/PartialUpdate.swift
- Sources/AlgoliaSearchClient/Models/Search/Indexing/PartialUpdateAction.swift
- Sources/AlgoliaSearchClient/Models/Search/MultipleIndex/SearchesResponse.swift
- Sources/AlgoliaSearchClient/Models/Search/Query/Auxiliary/Point.swift
- Sources/AlgoliaSearchClient/Models/Search/Query/Query+URLEncodable.swift
- Sources/AlgoliaSearchClient/Models/Search/Response/SearchResponse/Auxiliary/Highlighting/TaggedString.swift
- Sources/AlgoliaSearchClient/Models/Search/Response/SearchResponse/SearchResponse.swift
- Sources/AlgoliaSearchClient/Models/Settings/Auxiliary/LanguageFeature.swift
- Sources/AlgoliaSearchClient/Models/Settings/Settings.swift
- Sources/AlgoliaSearchClient/Transport/HTTP/HTTPTransport+Error.swift
- Sources/AlgoliaSearchClient/Transport/RetryStrategy/AlgoliaRetryStrategy.swift
- Sources/AlgoliaSearchClient/Transport/RetryStrategy/HostIterator.swift
- Sources/AlgoliaSearchClient/Transport/URLSession/URLRequest+Convenience.swift
- Tests/AlgoliaSearchClientTests/Unit/HitTests.swift
- Tests/AlgoliaSearchClientTests/Unit/PointTests.swift
**Summary**
Inspired by [Helpscout](https://secure.helpscout.net/conversation/1360178290) ticket
– Parsing doesn't fail if the format of Point for _geoloc is wrong
– Provide detailed error in case of Point parsing failure
– Add possibility to represent _geoloc as a list of points
> feat: hit _geoloc field improvement

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new minor version 8.4.0

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new patch version 8.4.1

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- README.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new patch version 8.4.2

- DOCKER_README.MD
- README.md
**Summary**
Add Docker readme and a Docker section in the main Readme. 
Resolves #700
> chore(docker): dockerize the repository

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- README.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new minor version 8.5.0

- Sources/AlgoliaSearchClient/Models/Rule/Rule+Condition.swift
- Tests/AlgoliaSearchClientTests/Unit/Rule/RuleConditionTests.swift
**Summary**
Adds `filters` field to the `Rule.Condition` structure
Fixes #718
> feat(rules): filters field in the Rule condition

- Sources/AlgoliaSearchClient/Models/Analytics/ABTest/Response/ABTestResponse+Variant.swift
- Sources/AlgoliaSearchClient/Models/Analytics/ABTest/Response/ABTestResponse.swift
> fix: AB test variant nullability

- Sources/AlgoliaSearchClient/Models/Common/CommonParameters.swift
- Sources/AlgoliaSearchClient/Models/Search/Query/Query+Codable.swift
- Sources/AlgoliaSearchClient/Models/Search/Query/Query+URLEncodable.swift
- Sources/AlgoliaSearchClient/Models/Search/SearchParameters.swift
- Sources/AlgoliaSearchClient/Models/Search/SearchParametersStorage.swift
- Sources/AlgoliaSearchClient/Models/Settings/SettingsParametersCodingKeys.swift
- Sources/AlgoliaSearchClient/Models/Settings/SettingsParametersStorage.swift
- Tests/AlgoliaSearchClientTests/Doc/APIParameters/APIParameters+Languages.swift
- Tests/AlgoliaSearchClientTests/Misc/Settings.json
- Tests/AlgoliaSearchClientTests/Unit/QueryTests.swift
- Tests/AlgoliaSearchClientTests/Unit/Settings/SettingsTests.swift
> feat(search/settings): decompoundQuery attribute as search/settings parameter

- Sources/AlgoliaSearchClient/Models/Settings/SettingsParameters.swift
- Sources/AlgoliaSearchClient/Models/Settings/SettingsParametersCodingKeys.swift
- Sources/AlgoliaSearchClient/Models/Settings/SettingsParametersStorage.swift
- Tests/AlgoliaSearchClientTests/Doc/APIParameters/APIParameters+Languages.swift
- Tests/AlgoliaSearchClientTests/Misc/Settings.json
- Tests/AlgoliaSearchClientTests/Unit/Settings/SettingsTests.swift
**Summary**
Adds `attributesToTransliterate` settings parameter
Fixes #715
> feat(settings): attributesToTransliterate parameter

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- README.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new minor version 8.6.0

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- README.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new minor version 8.7.0

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- README.md
- Sources/AlgoliaSearchClient/Helpers/FoundationConvenience/Data+JSONString.swift
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new minor version 8.8.0

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new patch version 8.8.1

- Sources/AlgoliaSearchClient/Models/Search/Query/Query+Codable.swift
- Sources/AlgoliaSearchClient/Models/Search/Query/Query+URLEncodable.swift
- Sources/AlgoliaSearchClient/Models/Search/Response/SearchResponse/SearchResponse+Codable.swift
**Summary**
This PR fixes the missing coding logic for the virtual replicas related parameters in the Query and the SearchResponse
> fix(virtual indices): add missing virtual replicas parameter coding

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new minor version 8.9.0

- Sources/AlgoliaSearchClient/Transport/RetryStrategy/RetryableHost.swift
**Summary**
Make the RetryableHist initialiser public to allow the initialization of the Client with a custom host
> fix(RetryableHost): Make the RetryableHost initializer public

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- README.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new minor version 8.10.0

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new minor version 8.12.0

- Sources/AlgoliaSearchClient/Helpers/UserAgent/UserAgent.swift
- Sources/AlgoliaSearchClient/Helpers/UserAgent/UserAgentController.swift
- Sources/AlgoliaSearchClient/Transport/HTTP/HTTPRequestBuilder.swift
**Summary**
User-agent controller refactoring which makes possible to set a dynamically changed user-agent component.
> feat: Dynamic user agents

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- README.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new minor version 8.13.0

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new patch version 8.13.1

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new patch version 8.13.3

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new patch version 8.13.4

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- README.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new minor version 8.14.0

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- README.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new minor version 8.15.0

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new patch version 8.15.1

- .github/workflows/carthage.yml
- .github/workflows/deployment.yml
- .github/workflows/pods.yml
- .github/workflows/tests.yml
**Summary**
- Add Carthage CI check
- Bump macOS and Xcode versions in the existing checks
> chore(ci): add Carthage CI check 

- Sources/AlgoliaSearchClient/Helpers/DisjunctiveFacetingHelper.swift
- Sources/AlgoliaSearchClient/Index/Index+Search.swift
- Tests/AlgoliaSearchClientTests/Unit/DisjunctiveFacetingHelperTests.swift
**Summary**
Adds search with disjunctive faceting method
**Result**
Fix #684
> feat(search): Disjunctive Faceting

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- README.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new minor version 8.16.0

- Sources/AlgoliaSearchClient/Client/AnalyticsClient.swift
- Sources/AlgoliaSearchClient/Index/Index+Indexing.swift
- Sources/AlgoliaSearchClient/Models/APIKey/APIKeyRevision.swift
- Sources/AlgoliaSearchClient/Models/Places/Country.swift
- Sources/AlgoliaSearchClient/Transport/HTTP/HTTPRequestBuilder.swift
- Tests/AlgoliaSearchClientTests/Integration/InsightsIntegrationTests.swift
**Summary**
Fixes lint issues
**Result**
Lint CI step succeed
> chore: fix lint issues

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new minor version 8.18.0

- Sources/AlgoliaSearchClient/Models/Common/Region.swift
- Sources/AlgoliaSearchClient/Models/Search/Query/Query+Codable.swift
- Sources/AlgoliaSearchClient/Models/Settings/Auxiliary/RankingCriterion.swift
- Sources/AlgoliaSearchClient/Transport/RetryStrategy/AlgoliaRetryStrategy.swift
**Summary**
Fix SwiftLint issues
**Result**
No lint warnings
> chore: lint issues

- .github/workflows/carthage.yml
- .github/workflows/lint.yml
- .github/workflows/pods.yml
**Summary**
Update CI checks triggers to make it work properly with external pull requests
> chore: update CI triggering

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- README.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new patch version 8.18.1

- Sources/AlgoliaSearchClient/Helpers/DisjunctiveFacetingHelper.swift
- Sources/AlgoliaSearchClient/Helpers/Wait/WaitableWrapper.swift
- Sources/AlgoliaSearchClient/Models/Insights/Event/EventType.swift
- Sources/AlgoliaSearchClient/Models/Insights/Event/InsightsEvent.swift
- Sources/AlgoliaSearchClient/Models/Insights/InsightsEvent+Resources.swift
- Sources/AlgoliaSearchClient/Models/Logs/LogType.swift
- Sources/AlgoliaSearchClient/Models/Search/Response/MultiSearchResponse.swift
**Summary**
This PR provides `CustomStringConvertible` protocol implementations for `InsightsEvent` and underlying structures to improve the logs readability.
> chore(insights): improve events logs

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new patch version 8.18.2

- .github/workflows/deployment.yml
- fastlane/Fastfile
**Summary**
Update deployment action
> chore: update deployment action

- AlgoliaSearchClient.podspec
- CHANGELOG.md
- README.md
- Sources/AlgoliaSearchClient/Helpers/Version+Current.swift
> chore: Deploying new minor version 8.19.0

- Sources/AlgoliaSearchClient/Models/Analytics/AnalyticsConfiguration.swift
- Sources/AlgoliaSearchClient/Models/Internal/Hosts.swift
**Summary**
Support of analytics region support is missing from the client
**Result**
This PR adds the support of region configuration for analytics client.
> fix(analytics): add region support

- AlgoliaSearchClient.podspec
- Package.swift
- PrivacyInfo.xcprivacy
**Summary**
Add the newly required Apple privacy manifest
> chore: add privacy manifest
