Source/Client.swift
When requesting with a poor connection it is possible that `data` is sent as `nil` with a `200` status code, we saw a lot of crashes in our logs around this with users on poor connections.
Added checks for `nil` data so we error out with the default error instead of crash.
=> Fixing nil data crash

Source/Network.swift, Tests/ClientTests.swift
We're seeing `SIGTRAP` crashes in prod on poor connections caused by the forced `try!` when serialising JSON
```
0x000a71a8 _TFFV4Manager7requestFS0_FTOS_10HTTPMethodSS10parametersGSqGVSs10DictionarySSPSs9AnyObject___5blockFTGSqCSo17NSHTTPURLResponse_GSqPS3___GSqCSo7NSError__T__VS_7RequestU_FTGSqCSo6NSData_GSqCSo13NSURLResponse_GSqS5___T_ + 190 (algoliasearch-client-swift_Network.swift:92)
```
request:
```
Method: POST	Error Code: -1001	Error: NSURLErrorTimedOut
14	/query
```
this should take care of it by not forcing the try.
=> NSJSONSerialization crashes

Tests/ClientTests.swift
We must wait for the index to be built, otherwise the test is not deterministic.
=> Fix “keep-alive” test case

Source/Client.swift, Source/Network.swift, Tests/ClientTests.swift
As per Apple’s docs, changing the configuration of an `NSURLSession` instance after its initialization has no effect. As a consequence, new values for HTTP headers failed to be taken into account.
Now, only immutable headers are passed during the session’s initialization. Other headers are stored in the `Client` instance, and explicitly passed at every request.
The HTTP headers are a key-value store (`[String: String]` dictionary). Dynamic properties are now built on top of this store.
NOTE: Some security-related headers have been marked as deprecated, since the preferred way is now to use secured API keys.
Fixes #13, fixes #27.
=> HTTP headers can now be changed during the session’s lifetime

Source/Client.swift, Source/Index.swift
All paths are missing the leading `/` which breaks `RFC 3986`, Apple complies to this which caused a discrepancy when cancelling requests
> Per RFC 3986, the leading slash after the authority (host name and port) portion is treated as part of the path. For example, in the URL http://www.example.com/index.html, the path is /index.html.
this logic below, was trying to match `path/to/url` with the `NSURLRequest` `/path/to/url` which will always fail
```
if request.request.URL!.path! == path
```
I can't get the unit tests running locally due to the `ClientTests` timing out on exceptions on master so :warning:
=> Fix cancelQueries

Tests/ClientTests.swift
There is no way to reliably test the keep-alive feature, as `NSURLSession` controls it automatically. This test case is causing random but frequent failures in Travis, although the connection does appear to be kept alive (`Connection: keep-alive` sent by server) in most cases.
=> Remove test case for keep-alive

Source/Query.swift, Tests/IndexTests.swift, Tests/QueryTests.swift
The rationale for not implementing them was that they cannot be adequately typed. However, after investigation:
- `numericFilters` has roughly the same complexity as `tagFilters` or `facetFilters`. Therefore using a JSON array type, like for those parameters, should be adequate (although suboptimal).
- `filters` is designed to be a “SQL-like notation”, so I guess a raw string type is adequate. In the future, we may want to provide tools to build the filters more easily, but this will likely come in the form of “helpers”, as it is done in the Javascript client.
Since the absence of typed properties for the missing parameters was confusing, I am adding them now.
=> Add missing query parameters `filters` and `numericFilters`

AlgoliaSearch-Client-Swift.podspec, AlgoliaSearch.xcodeproj/project.pbxproj, Source/Client.swift
- Move deployment target to iOS 7.0 (was 8.0).
- Remove obsolete queue in `Client` class (`underlyingQueue` property not supported on iOS 7).
Fixes #63.
=> Support iOS 7.0

Source/Client.swift, Tests/ClientTests.swift
`Client.isAlive()` just pings `/1/isalive`.
=> Implement the “is alive” endpoint

Source/Client.swift, Tests/ClientTests.swift
**WARNING: Breaking change.** Multiple queries are just aggregated search queries, so it does not make any sense to ignore the results. Furthermore, it contradicts the convention adopted in the rest of the code.
=> Make completion handler mandatory on multiple queries

Source/Client.swift, Source/Helpers.swift, Source/Index.swift, Source/Query.swift, Tests/ClientTests.swift
- Spaces must be properly escaped, otherwise the URL is invalid, and results in a crash (fixes #103).
- Query parameters have a different allowed character set and must be escaped accordingly. This was already the case inside the `Query` class, but not for the few query parameters set in the `Client` or `Index` classes. => This behavior is now factorized in the helper `String` extension.
=> Fix URL encoding of path components and query strings

Source/Query.swift
NOTE: This is a build-time setting, so it is *not* part of the `Query` class. But it is mentioned in the docs.
WARNING: Wait for the new parameter to be implemented before merging this PR!
=> Rename `attributesToIndex` to `searchableAttributes`

Source/Index.swift, Tests/IndexTests.swift, Tests/ObjectiveCBridging.m
- Add a new method `Index.searchFacet(_:for:query:completionHandler:)` targeting the `POST /1/indexes/${indexName}/facets/${facetName}/query/` API endpoint.
- Swift unit test
- Objective-C bridging test
=> Add support for search in facet values

Source/AbstractClient.swift, Source/Request.swift, Tests/ClientTests.swift, Tests/Helpers.swift, Tests/IndexTests.swift, Tests/NetworkTests.swift, Tests/ObjectiveCBridging.m
The client now keeps an up/down status for each of its hosts, and avoids targeting down hosts, unless their status is considered obsolete, as per the time frame indicated by `hostStatusesTimeout`.
This way, if a host is down for any reason (DNS resolution, routing problem, server down…), it will be ignored for subsequent requests, until the status timeout has expired.
=> Stateful host statuses

AlgoliaSearch.xcodeproj/project.pbxproj, Source/Helpers.swift, Source/Index.swift, Source/Offline/MirroredIndex.swift, Source/Offline/OfflineIndex.swift, Tests/IndexTests.swift, Tests/Offline/MirroredIndexTests.swift, Tests/Offline/OfflineClientTests.swift, Tests/Offline/OfflineIndexTests.swift, Tests/Offline/OfflineObjcBridging.m, Tests/Offline/OfflineTestCase.swift, Tests/Offline/objects.json, Tests/Offline/settings.json, offline.jazzy.yaml, tools/make-doc.sh
- Manually build a `MirroredIndex` or an `OfflineIndex` from local files. Combined with a new `hasOfflineData` property, this allows **bootstrapping** a mirrored index before the first sync.
- Get individual objects directly from the local mirror of a `MirroredIndex`, or use the same fallback policy as search.
=> New offline features

Source/Query.swift, Tests/QueryTests.swift
This parameter is implemented at the `Query` class level, although it only applies to searches for facet values (not to regular searches).
=> Support `maxFacetHits` when searching for facet values

AlgoliaSearch-Offline-Swift.podspec, Podfile, Source/Offline/MirroredIndex.swift, Source/Offline/OfflineIndex.swift, Tests/Offline/MirroredIndexTests.swift, Tests/Offline/OfflineIndexTests.swift, Tests/Offline/OfflineTestCase.swift
Implement offline search for facet values, just like for regular search:
- on `MirroredIndex` with request strategy
- on `OfflineIndex` for pure offline request
Requires Offline Core 1.1.0, which is out now.
=> Support offline search for facet values

AlgoliaSearch.xcodeproj/project.pbxproj, Source/AbstractClient.swift, Source/Index.swift, Source/Offline/OfflineClient.swift, Source/Offline/OfflineIndex.swift, Source/Request.swift, Source/Searchable.swift, Tests/ClientTests.swift, Tests/ObjectiveCBridging.m
This unites all indices (`Index`, `MirroredIndex` and `OfflineIndex`) under a common protocol, which can be leveraged in InstantSearch Core to support searching on an offline index.
Making the `User-Agent` header static means other libraries (InstantSearch Core again) can easily update the user agent without having to obtain a `Client` instance. (Will be required to leverage `Searchable` in the `Searcher` class.)
=> New `Searchable` protocol & static `User-Agent` header

Source/AbstractQuery.swift, Tests/QueryTests.swift
Added at the `AbstractQuery` level, so it’s available for both `Query` and `PlacesQuery`.
=> Add KVO support to query classes

Source/AbstractClient.swift, Source/AsyncOperation.swift, Source/Client.swift, Source/Index.swift, Source/Offline/MirroredIndex.swift, Source/Offline/OfflineClient.swift, Source/Offline/OfflineIndex.swift, Tests/ClientTests.swift, Tests/ObjectiveCBridging.m
By default, the main queue is used.
Fixes #69.
=> Add an option to choose a custom queue for completion handlers

Source/Query.swift, Tests/QueryTests.swift
When converting Doubles to String we lose precision if we don't use the String() way. If we use the JSONSerializer, everything is converted to Data and then to String which will end with converting 22.2222 to something like 22.22222000000000008
=> Fix Double conversion for the Polygon query

AlgoliaSearch.xcodeproj/project.pbxproj, Source/AbstractClient.swift, Source/Client.swift, Source/Index.swift, Source/Offline/MirroredIndex.swift, Source/Offline/OfflineIndex.swift, Source/Request.swift, Source/RequestOptions.swift, Source/Searchable.swift, Tests/ClientTests.swift
Adds support for per-request options. The request options are for now an empty shell allowing to override the headers. They will be leveraged in the future to add specific options.
=> Per-request options

Sources/AlgoliaSearch-Client/AbstractClient.swift, Sources/AlgoliaSearch-Client/Helpers/DisjunctiveFaceting.swift, Sources/AlgoliaSearch-Client/Network.swift, Sources/AlgoliaSearch-Client/Request.swift, Tests/Helpers/MockURLSession.swift, Tests/Integration Tests/IndexTests.swift
In InstantSearch-Core-Swift project, I find that `content["facets_stats"]` in `SearchResults` class is always `nil`. After debugging with some break points, I found the function `_aggregateResults` in `DisjunctiveFaceting` class. It is in this function we construct `content` dictionary mentioned above, and it is in this function we lose all facet stats values. So in addition to aggregate all values under `"facets"` key from the raw json response, we should also aggregate all values under `"facets_stats"` key.
=> Aggregate facets_stats

fastlane/Fastfile
Deployment commit is now through a PR instead of force push due to protected branch
=> ci(pr): deployment commit is now through a PR 

Package.swift
It does not correctly build for Swift 4.2 here, so removing it.
=> Fix SPM Swift 5 issue

Sources/AlgoliaSearch-Client/Network.swift, Sources/AlgoliaSearch-Client/Version.swift
This fix addresses the [issue ](https://github.com/algolia/instantsearch-core-swift/issues/103) making impossible the usage of Swift Client for universal Catalyst app development starting from Xcode 11.4
=> Exclude CoreTelephony dependent code from Mac Catalyst app

Sources/AlgoliaSearchClient/Models/Settings/Settings+Codable.swift, Sources/AlgoliaSearchClient/Models/Settings/Settings.swift, Tests/AlgoliaSearchClientTests/Misc/Settings.json, Tests/AlgoliaSearchClientTests/Unit/Settings/SettingsTests.swift
=> feat(Settings): Accept `enablePersonalization` boolean as a valid setting parameter

Sources/AlgoliaSearchClient/Command/Command+Personalization.swift, Sources/AlgoliaSearchClient/Models/Internal/HTTP/HTTPStatusCode.swift, Tests/AlgoliaSearchClientTests/Integration/PersonalizationIntegrationTests.swift, Tests/AlgoliaSearchClientTests/Unit/Command/PersonalizationCommandTests.swift
The personalization API is now limiting the number of setPersonalizationStrategy() successful calls
to 15 per day. If the 429 error is returned, the response is considered a success.
Fixes: #647
=> fix(personalization_strategy): prevent error in CTS personalization test on 429 HTTP code

Sources/AlgoliaSearchClient/Models/Places/PlacesQuery.swift
This PR adds the documentation clarifying how to set  implicitly the `language` parameter of `PlacesQuery`.
Fixes #655
=> feat(PlacesQuery): Add clarification for language parameter of PlacesQuery

Sources/AlgoliaSearchClient/Transport/HTTP/HTTPRequest.swift, Sources/AlgoliaSearchClient/Transport/HTTP/HTTPRequestBuilder.swift, Sources/AlgoliaSearchClient/Transport/HTTP/HTTPTransport+Error.swift, Sources/AlgoliaSearchClient/Transport/HTTP/HTTPTransport+Result.swift, Sources/AlgoliaSearchClient/Transport/RetryStrategy/AlgoliaRetryStrategy.swift, Sources/AlgoliaSearchClient/Transport/RetryStrategy/HostIterator.swift, Sources/AlgoliaSearchClient/Transport/RetryStrategy/RetryStrategy.swift, Tests/AlgoliaSearchClientTests/Unit/AlgoliaRetryStrategyTests.swift
**Summary**
This PR fixes the implementation of the retry strategy. 
Previously after finishing the hosts iteration, the strategy reset the hosts and started the polling again.
It led to infinite host polling loop and no error occured in case of missing internet connection, for example.    
**Result**
With the fixes applied in this PR, the retry strategy iterates the host list only once per request.  
Fixes #664
=> Fix retry strategy behaviour if all the hosts are unreachable

Sources/AlgoliaSearchClient/Command/Command+Search.swift, Sources/AlgoliaSearchClient/Transport/URLSession/URLRequest+Convenience.swift, Tests/AlgoliaSearchClientTests/Unit/Command/SearchCommandTests.swift, Tests/AlgoliaSearchClientTests/Unit/TestValues.swift
This PR implements the explicit percent encoding for plus sign for browse cursor, lack of which causes browse call error.
=> Add explicit percent encoding for plus sign for the browsing cursor

Package.swift
**Summary**
After trying to use the Algolia Search Client with SPM, I've noticed that for some reason, the dependency of the Logging (https://github.com/apple/swift-log) is not fully satisfied the targeting the min iOS version to 8.0. To fix the problem, we should update the min version to at least 9.0. I've also update the log version to 1.4.0 since it doesn't introduce any bugs.
**Result**
Nothing in special, you should be able to download the lib via SPM and build your project without problems.
=> Updated min ios version and log version

AlgoliaSearchClient.podspec, Sources/AlgoliaSearchClient/Command/Command+Search.swift, Sources/AlgoliaSearchClient/Helpers/Version+Current.swift, Sources/AlgoliaSearchClient/Index/Index+Search.swift, Sources/AlgoliaSearchClient/Models/Data structures/FieldWrapper.swift, Tests/AlgoliaSearchClientTests/Integration/BrowseIntegrationTests.swift, Tests/AlgoliaSearchClientTests/Unit/Command/SearchCommandTests.swift
**Summary**
This PR changes the HTTP method of the browse with cursor call from GET to POST.
It makes Swift API client aligned with other strongly typed clients such as Java and C# clients avoiding ussues with encoding the cursor as an URL parameter.
Resolves #675
=> fix(Browse): change browse with cursor method GET -> POST 

Sources/AlgoliaSearchClient/Models/Analytics/ABTest/Response/ABTestResponse+Variant.swift
**Summary**
Resolves [this issue](https://github.com/algolia/algoliasearch-client-specs-internal/issues/143)
=> fix: set ABTestResponse.Variant.averageClickPosition type `Double` 

Sources/AlgoliaSearchClient/Models/Search/Response/SearchResponse/Auxiliary/Highlighting/HighlightedString.swift, Tests/AlgoliaSearchClientTests/Unit/HighlightedStringTests.swift
**Summary**
Set highlighting tag parsing diacritic insensitive to avoid crashes while calculating highlighted subranges.
=> fix: Set tag parsing for highlighted strings diacritic insensitive

fastlane/Fastfile
**Summary**
Set the check of the branch name and its cleanliness for Bitrise as it works with detached HEAD state.
=> ci: remove check of the branch name and its cleanliness for Bitrise in depolyment script

Sources/AlgoliaSearchClient/Models/Search/Response/SearchResponse/Auxiliary/Highlighting/TaggedString.swift, Tests/AlgoliaSearchClientTests/Unit/HighlightedStringTests.swift, Tests/AlgoliaSearchClientTests/Unit/TaggedStringTests.swift
**Summary**
Currently the `TaggedString` properties used for results highlighting are calculated at the instantiation time (complexity O(n)).
This PR makes the calculation of these properties lazy, so the calculation happens only when they are actually required. 
*Advantages*
- Performance gain
- Crashes
*Consequences* 
- A mutable copy of `TaggedString` must be created to access the lazy properties, as the lazy properties are `mutating`. 
- `InstantSearch` must be updated to satisfy the previous condition
=> perf: Tagged string lazy property calculation

Sources/AlgoliaSearchClient/Command/Command+Synonym.swift, Sources/AlgoliaSearchClient/Index/Index+Synonym.swift, Sources/AlgoliaSearchClient/Models/Common/RequestOptions.swift, Tests/AlgoliaSearchClientTests/Doc/Methods/SynonymsSnippets.swift, Tests/AlgoliaSearchClientTests/Unit/Command/SynonymCommandTests.swift
**Summary**
Rename `replaceExistingSynonyms` -> `clearExistingSynonyms`
Fixes #694
=> refactor: rename replaceExistingSynonyms into clearExistingSynonyms

Sources/AlgoliaSearchClient/Transport/RetryStrategy/AlgoliaRetryStrategy.swift, Tests/AlgoliaSearchClientTests/Unit/AlgoliaRetryStrategyTests.swift
**Summary**
This fix adds synchronisation to HostIterator callback provided by retry strategy to avoid crash due to concurrent access to the list of hosts
Fixes #705
=> fix: HostIterator crash

Sources/AlgoliaSearchClient/Client/InsightsClient.swift, Sources/AlgoliaSearchClient/Command/Command+Insights.swift, Tests/AlgoliaSearchClientTests/Unit/Command/InsightsCommandTest.swift
**Summary**
Move required `content-type` header from synchronous `InsightsClient.sendEvents` function to `Command.Insights.SendEvents` structure.
**Result**
Insights events sent correctly using async `sendEvents` method
=> fix: Missing content-type header for async InsightsClient.sendEvents call

Sources/AlgoliaSearchClient/Models/Search/Response/SearchResponse/SearchResponse+Codable.swift
=> fix: Set the correct json decoding key for indexName field in the SearchResponse

Sources/AlgoliaSearchClient/Helpers/FoundationConvenience/TimeInterval+Minutes.swift, Tests/AlgoliaSearchClientTests/Doc/Methods/ABTestSnippets.swift, Tests/AlgoliaSearchClientTests/Doc/Methods/APIKeysSnippets.swift, Tests/AlgoliaSearchClientTests/Doc/Methods/RulesSnippets.swift
**Summary**
The convenient TimeInterval methods defined in the extensions conflict with the methods defined for  `DispatchTimeInterval` type which leads to compile errors. 
This PR makes the TimeInterval convenience extension internal to avoid this conflict.
Fix #737
=> fix: Resolve conflict between TimeInterval convenient methods and DispatchTimeInterval

Sources/AlgoliaSearchClient/Models/Search/Response/SearchResponse/SearchResponse+Codable.swift, Sources/AlgoliaSearchClient/Models/Search/Response/SearchResponse/SearchResponse.swift
**Summary**
Adds `abTestID` field to the search response
Fix #748
=> feat(analytics): Add `abTestID` to the search response

Sources/AlgoliaSearchClient/Models/Search/Query/Auxiliary/AroundPrecision.swift, Tests/AlgoliaSearchClientTests/Unit/QueryTests.swift
**Summary**
The `aroundPrecision` value uses floating point types not supported by the engine.
This PR changes its type to Integer.
=> fix: Around precision url component conversion issue

Sources/AlgoliaSearchClient/Command/Command+ABTest.swift, Sources/AlgoliaSearchClient/Command/Command+APIKeys.swift, Sources/AlgoliaSearchClient/Command/Command+Advanced.swift, Sources/AlgoliaSearchClient/Command/Command+Insights.swift, Sources/AlgoliaSearchClient/Command/Command+MultiCluster.swift, Sources/AlgoliaSearchClient/Command/Command+MultipleIndex.swift, Sources/AlgoliaSearchClient/Command/Command+Personalization.swift, Sources/AlgoliaSearchClient/Command/Command.swift, Sources/AlgoliaSearchClient/Helpers/UserAgent/UserAgent.swift, Sources/AlgoliaSearchClient/Helpers/UserAgent/UserAgentController.swift, Sources/AlgoliaSearchClient/Transport/URLSession/URLRequest+Convenience.swift, Tests/AlgoliaSearchClientTests/Unit/Transport/HostSwitcherTests.swift, Tests/AlgoliaSearchClientTests/Unit/Transport/URLRequestConstructionTests.swift
**Summary**
If the API key's length is bigger than 500 characters it cannot be sent via request header. 
This PR adds the logic which moves the API key to the request body (if applicable) in this case. 
Fixes #766
=> fix(longAPIKey): Move API key to body if the key's length > 500 chars

Sources/AlgoliaSearchClient/Models/Search/Query/Query+URLEncodable.swift, Tests/AlgoliaSearchClientTests/Unit/QueryTests.swift
**Summary**
The plus signs in the query parameters is not properly percent encoded when query parameters are encoded as URL. 
This PR fixes this issue.
=> fix: Query url plus sign percent encoding 

Sources/AlgoliaSearchClient/Models/Search/Response/ObjectsResponse.swift
**Summary**
The generic T type used for `results` value of the `ObjectsResponse` type has a `Codable` (alias for `Encodable & Decodable`) constraint, while the `Decodable` constraint is enough.
Reported [here](https://algolia.atlassian.net/jira/software/c/projects/CR/boards/189?modal=detail&selectedIssue=CR-565&quickFilter=459)
**Result**
Possibility to use types conforming to `Decodable`  in `ObjectsResponse` instead of `Encodable & Decodable`.
=> fix: Change ObjectsResponse results type constraint Codable -> Decodable 

Sources/AlgoliaSearchClient/Client/AccountClient.swift, Sources/AlgoliaSearchClient/Helpers/ResultCallback.swift, Sources/AlgoliaSearchClient/Helpers/Wait/WaitableWrapper.swift, Sources/AlgoliaSearchClient/Index/Index+Advanced.swift, Sources/AlgoliaSearchClient/Index/Index.swift, Sources/AlgoliaSearchClient/Models/Analytics/ABTest/Task/ABTestCreation.swift, Sources/AlgoliaSearchClient/Models/Analytics/ABTest/Task/ABTestDeletion.swift, Sources/AlgoliaSearchClient/Models/Analytics/ABTest/Task/ABTestRevision.swift, Sources/AlgoliaSearchClient/Models/Common/Revision.swift, Sources/AlgoliaSearchClient/Models/Search/Indexing/Batch/BatchResponse.swift, Sources/AlgoliaSearchClient/Models/Synonym/SynonymRevision.swift, Sources/AlgoliaSearchClient/Models/Task/Common/IndexTask.swift, Sources/AlgoliaSearchClient/Models/Task/Index/IndexDeletion.swift, Sources/AlgoliaSearchClient/Models/Task/Index/IndexRevision.swift, Sources/AlgoliaSearchClient/Models/Task/Index/IndexedTask.swift, Sources/AlgoliaSearchClient/Models/Task/Object/ObjectCreation.swift, Sources/AlgoliaSearchClient/Models/Task/Object/ObjectDeletion.swift, Sources/AlgoliaSearchClient/Models/Task/Object/ObjectRevision.swift, Sources/AlgoliaSearchClient/Transport/Common/TransportContainer.swift, Tests/AlgoliaSearchClientTests/Doc/Methods/ManageIndicesSnippets.swift
**Summary**
The `Task` protocol used in the client conflicts with the [`Task`](https://developer.apple.com/documentation/swift/task) structure introduced with the Swift concurrency.
This PR renames the protocol  `Task` to `IndexTask`.
The introduced naming is also more consistent, as the client contains the `AppTask` protocol used for [custom dictionaries method](https://github.com/algolia/algoliasearch-client-swift/pull/717). 
While this change seems to be breaking, it doesn't affect the final implementations, as the protocol is not designed to be used directly, it's used as a generic constraint internally.
=> refactor: rename Task -> IndexTask

Sources/AlgoliaSearchClient/Models/Common/Region.swift, Sources/AlgoliaSearchClient/Models/Internal/Hosts.swift, Sources/AlgoliaSearchClient/Models/Personalization/PersonalizationConfiguration.swift, Tests/AlgoliaSearchClientTests/Integration/PersonalizationIntegrationTests.swift
**Summary**
- Replace the legacy `recommendation` host with `personalization` host for Personalization client
- Add convenient "eu" constant for `Region` type to use with Personalization client
=> chore: update host for Personalization Client

Sources/AlgoliaSearchClient/Transport/RetryStrategy/AlgoliaRetryStrategy.swift
Hello!
I was trying to compile this client as a dependency on a server-side application running on Linux. I would get an error that `URLRequest` was not defined in the file `AlgoliaRetryStrategy.swift`. I believe this was due to the lack of a conditional import of `FoundationNetworking`, so this PR just adds that.
This library now seems to compile correctly on Linux with this change.
Thanks for all the work on this client!
=> fix: added conditional FoundationNetworking import

Sources/AlgoliaSearchClient/Transport/HTTP/HTTPTransport+Error.swift
**Summary**
Changes the implementation of the `errorDescription` method of the `TransportError` to improve its readability in the logs.
=> chore: improve readability of the TransportError description

Sources/AlgoliaSearchClient/Transport/RetryStrategy/AlgoliaRetryStrategy.swift, Tests/AlgoliaSearchClientTests/Integration/PersonalizationIntegrationTests.swift, Tests/AlgoliaSearchClientTests/Unit/Transport/AlgoliaRetryStrategyTests.swift, Tests/AlgoliaSearchClientTests/Unit/Transport/HTTPRequestTests.swift
**Summary**
This PR fixes pattern matching issue in the retry strategy that causes incorrect operation of the retry strategy in some cases.
**Result**
Retry strategy works correctly.
=> fix: matching errors in the retry strategy

Sources/AlgoliaSearchClient/Transport/RetryStrategy/RetryableHost.swift
**Summary**
Remove dead `timeout` function from the `RetryableHost`
=> chore: remove dead timeout function from RetryableHost

Sources/AlgoliaSearchClient/Index/Index+Search.swift, Sources/AlgoliaSearchClient/Models/Settings/Auxiliary/CustomRankingCriterion.swift
**Summary**
Adds missing custom request options to `searchDisjunctiveFaceting` method. 
**Result**
`searchDisjunctiveFaceting` method can be customized with request options
=> feat(search disjunctive faceting): add request options

Sources/AlgoliaSearchClient/Helpers/DisjunctiveFacetingHelper.swift, Tests/AlgoliaSearchClientTests/Unit/DisjunctiveFacetingHelperTests.swift
**Summary**
Solves [DI-2708]
There was a discrepancy between v7 and v8 of the client where the helper began using the `filters` property instead of the `facetFilters` property, as recommended by the official Algolia documentation, but not taking into account that users may already be using the property.
We needed to make sure existing filters were preserved.
**Result**
The `filters` property is no longer overwritten.
[DI-2708]: https://algolia.atlassian.net/browse/DI-2708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(search): disjunctive faceting helper
